version: '3'
services:
  squoosh:
    image: dko0/squoosh:1.12.0
    container_name: squoosh
    networks:
      - squoosh-net
    ports:
      - 7701:8080
    restart: unless-stopped
networks:
  squoosh-net:
